/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Modelo.*;
import javax.swing.JOptionPane;
/**
 *
 * @author JESUS DANIEL
 */
public class Vista extends javax.swing.JFrame {
    
    Estudiante estudiante = new Estudiante();
    Materia materia = new Materia();
    Matricula matricula = new Matricula();
    Profesor profesor = new Profesor();
    /**
     * Creates new form Bista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estudiante_btnGroup_sexo = new javax.swing.ButtonGroup();
        jPanel_fondo_izquierda = new javax.swing.JPanel();
        btn_salir = new javax.swing.JButton();
        btn_profesor = new javax.swing.JButton();
        btn_materia = new javax.swing.JButton();
        btn_matricula = new javax.swing.JButton();
        btn_estudiante = new javax.swing.JButton();
        btn_nota = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_estudiante = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        estudiante_txt_nombre = new javax.swing.JTextField();
        estudiante_btn_guardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        estudiante_txt_edad = new javax.swing.JTextField();
        estudiante_txt_identificacion = new javax.swing.JTextField();
        estudiante_txt_direccion = new javax.swing.JTextField();
        estudiante_txt_telefono = new javax.swing.JTextField();
        estudiante_txt_correo = new javax.swing.JTextField();
        estudiante_txt_codigo = new javax.swing.JTextField();
        estudiante_jRadioButton_masculino = new javax.swing.JRadioButton();
        estudiante_jRadioButton_femenino = new javax.swing.JRadioButton();
        estudiante_jRadioButton_nobinario = new javax.swing.JRadioButton();
        jPanel_materia = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        materia_txt_nombre = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        materia_txt_codigo = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        profesor_btn_guardar1 = new javax.swing.JButton();
        materia_jComboBox_semestre = new javax.swing.JComboBox<>();
        materia_jComboBox_num_creditos = new javax.swing.JComboBox<>();
        jPanel_profesor = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        profesor_txt_codigo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        profesor_txt_nombre = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        profesor_btn_guardar = new javax.swing.JButton();
        profesor_jComboBox_tipo_de_vinculacion = new javax.swing.JComboBox<>();
        profesor_jComboBox_titulo = new javax.swing.JComboBox<>();
        jPanel_matricula = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        matricula_txt_codigo_estudiante = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        matricula_btn_guardar = new javax.swing.JButton();
        matricula_jComboBox_profesor = new javax.swing.JComboBox<>();
        matricula_jComboBox_materia = new javax.swing.JComboBox<>();
        matricula_jComboBox_periodo_academico = new javax.swing.JComboBox<>();
        jPanel_nota = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        nota_jComboBox_estudiante = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        nota_btn_guardar = new javax.swing.JButton();
        nota_txt_nota = new javax.swing.JTextField();
        nota_jComboBox_materia = new javax.swing.JComboBox<>();
        nota_jComboBox_profesor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidad");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_fondo_izquierda.setBackground(new java.awt.Color(64, 64, 64));

        btn_salir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_salir.setText("Salir");
        btn_salir.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_profesor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_profesor.setText("Profesor");
        btn_profesor.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_profesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profesorActionPerformed(evt);
            }
        });

        btn_materia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_materia.setText("Materia");
        btn_materia.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_materiaActionPerformed(evt);
            }
        });

        btn_matricula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_matricula.setText("Matricula");
        btn_matricula.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_matriculaActionPerformed(evt);
            }
        });

        btn_estudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_estudiante.setText("Estudiante");
        btn_estudiante.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estudianteActionPerformed(evt);
            }
        });

        btn_nota.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btn_nota.setText("Nota");
        btn_nota.setPreferredSize(new java.awt.Dimension(100, 30));
        btn_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_notaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_fondo_izquierdaLayout = new javax.swing.GroupLayout(jPanel_fondo_izquierda);
        jPanel_fondo_izquierda.setLayout(jPanel_fondo_izquierdaLayout);
        jPanel_fondo_izquierdaLayout.setHorizontalGroup(
            jPanel_fondo_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondo_izquierdaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel_fondo_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_fondo_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel_fondo_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel_fondo_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel_fondo_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel_fondo_izquierdaLayout.setVerticalGroup(
            jPanel_fondo_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_fondo_izquierdaLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btn_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel_fondo_izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 480));

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel_estudiante.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Nombre:");

        estudiante_txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiante_txt_nombreActionPerformed(evt);
            }
        });

        estudiante_btn_guardar.setText("Guardar");
        estudiante_btn_guardar.setPreferredSize(new java.awt.Dimension(100, 30));
        estudiante_btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiante_btn_guardarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Sexo:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Edad");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Identificación:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Telefono");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Dirección");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Correo");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Código:");

        estudiante_txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiante_txt_edadActionPerformed(evt);
            }
        });

        estudiante_txt_identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiante_txt_identificacionActionPerformed(evt);
            }
        });

        estudiante_txt_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiante_txt_direccionActionPerformed(evt);
            }
        });

        estudiante_txt_telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiante_txt_telefonoActionPerformed(evt);
            }
        });

        estudiante_txt_correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiante_txt_correoActionPerformed(evt);
            }
        });

        estudiante_txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiante_txt_codigoActionPerformed(evt);
            }
        });

        estudiante_btnGroup_sexo.add(estudiante_jRadioButton_masculino);
        estudiante_jRadioButton_masculino.setText("Masculino");

        estudiante_btnGroup_sexo.add(estudiante_jRadioButton_femenino);
        estudiante_jRadioButton_femenino.setText("Femenino");
        estudiante_jRadioButton_femenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estudiante_jRadioButton_femeninoActionPerformed(evt);
            }
        });

        estudiante_btnGroup_sexo.add(estudiante_jRadioButton_nobinario);
        estudiante_jRadioButton_nobinario.setText("No binario");

        javax.swing.GroupLayout jPanel_estudianteLayout = new javax.swing.GroupLayout(jPanel_estudiante);
        jPanel_estudiante.setLayout(jPanel_estudianteLayout);
        jPanel_estudianteLayout.setHorizontalGroup(
            jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_estudianteLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(estudiante_btn_guardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel_estudianteLayout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(18, 18, 18)
                            .addComponent(estudiante_txt_direccion))
                        .addGroup(jPanel_estudianteLayout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(estudiante_txt_telefono))
                        .addGroup(jPanel_estudianteLayout.createSequentialGroup()
                            .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(estudiante_txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(estudiante_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel_estudianteLayout.createSequentialGroup()
                                    .addComponent(estudiante_jRadioButton_masculino)
                                    .addGap(71, 71, 71)
                                    .addComponent(estudiante_jRadioButton_femenino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(estudiante_jRadioButton_nobinario))))
                        .addGroup(jPanel_estudianteLayout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(estudiante_txt_identificacion))
                        .addGroup(jPanel_estudianteLayout.createSequentialGroup()
                            .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(estudiante_txt_codigo)
                                .addComponent(estudiante_txt_correo))))))
        );
        jPanel_estudianteLayout.setVerticalGroup(
            jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_estudianteLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(estudiante_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(estudiante_jRadioButton_masculino)
                    .addComponent(estudiante_jRadioButton_femenino)
                    .addComponent(estudiante_jRadioButton_nobinario))
                .addGap(20, 20, 20)
                .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(estudiante_txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(estudiante_txt_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(estudiante_txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estudiante_txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(estudiante_txt_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_estudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(estudiante_txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(estudiante_btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("tab1", jPanel_estudiante);

        jPanel_materia.setBackground(new java.awt.Color(204, 204, 204));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("Materia:");

        materia_txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materia_txt_nombreActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("Código:");

        materia_txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materia_txt_codigoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("Num de Creditos");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("Semestre ");

        profesor_btn_guardar1.setText("Guardar");
        profesor_btn_guardar1.setPreferredSize(new java.awt.Dimension(100, 30));
        profesor_btn_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesor_btn_guardar1ActionPerformed(evt);
            }
        });

        materia_jComboBox_semestre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materia_jComboBox_semestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "0", "1","2","3","4","5","6","7","8","9","10","11","12" }));
        materia_jComboBox_semestre.setPreferredSize(new java.awt.Dimension(28, 20));

        materia_jComboBox_num_creditos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        materia_jComboBox_num_creditos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "0", "1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16"}));
        materia_jComboBox_num_creditos.setPreferredSize(new java.awt.Dimension(28, 20));

        javax.swing.GroupLayout jPanel_materiaLayout = new javax.swing.GroupLayout(jPanel_materia);
        jPanel_materia.setLayout(jPanel_materiaLayout);
        jPanel_materiaLayout.setHorizontalGroup(
            jPanel_materiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_materiaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel_materiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(profesor_btn_guardar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_materiaLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(materia_jComboBox_num_creditos, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_materiaLayout.createSequentialGroup()
                        .addGroup(jPanel_materiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_materiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(materia_txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(materia_txt_codigo)))
                    .addGroup(jPanel_materiaLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addComponent(materia_jComboBox_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 85, Short.MAX_VALUE))
        );
        jPanel_materiaLayout.setVerticalGroup(
            jPanel_materiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_materiaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel_materiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(materia_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_materiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(materia_txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel_materiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(materia_jComboBox_num_creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_materiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(materia_jComboBox_semestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(profesor_btn_guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("tab3", jPanel_materia);

        jPanel_profesor.setBackground(new java.awt.Color(204, 204, 204));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Código:");

        profesor_txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesor_txt_codigoActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Nombre:");

        profesor_txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesor_txt_nombreActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Título:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Tipo de vinculación:");

        profesor_btn_guardar.setText("Guardar");
        profesor_btn_guardar.setPreferredSize(new java.awt.Dimension(100, 30));
        profesor_btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profesor_btn_guardarActionPerformed(evt);
            }
        });

        profesor_jComboBox_tipo_de_vinculacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        profesor_jComboBox_tipo_de_vinculacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Catedra", "Contrato a término fijo", "Tiempo completo", "Tiempo Parcial", "Hora Catedra","Nombramiento" }));
        profesor_jComboBox_tipo_de_vinculacion.setPreferredSize(new java.awt.Dimension(28, 20));

        profesor_jComboBox_titulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        profesor_jComboBox_titulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Doctor" ,"Especialista", "Licenciado" ,"Magíster" }));
        profesor_jComboBox_titulo.setPreferredSize(new java.awt.Dimension(28, 20));

        javax.swing.GroupLayout jPanel_profesorLayout = new javax.swing.GroupLayout(jPanel_profesor);
        jPanel_profesor.setLayout(jPanel_profesorLayout);
        jPanel_profesorLayout.setHorizontalGroup(
            jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_profesorLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(profesor_btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel_profesorLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addGap(18, 18, 18)
                            .addComponent(profesor_jComboBox_tipo_de_vinculacion, 0, 296, Short.MAX_VALUE))
                        .addGroup(jPanel_profesorLayout.createSequentialGroup()
                            .addGroup(jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(profesor_jComboBox_titulo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(profesor_txt_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                                .addComponent(profesor_txt_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)))))
                .addGap(8, 85, Short.MAX_VALUE))
        );
        jPanel_profesorLayout.setVerticalGroup(
            jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_profesorLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(profesor_txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(profesor_txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(profesor_jComboBox_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_profesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(profesor_jComboBox_tipo_de_vinculacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(profesor_btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("tab2", jPanel_profesor);

        jPanel_matricula.setBackground(new java.awt.Color(204, 204, 204));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("Código del Estudiante:");

        matricula_txt_codigo_estudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula_txt_codigo_estudianteActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel24.setText("Materia:");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Profesor");

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel26.setText("Periodo Academico:");

        matricula_btn_guardar.setText("Guardar");
        matricula_btn_guardar.setPreferredSize(new java.awt.Dimension(100, 30));
        matricula_btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula_btn_guardarActionPerformed(evt);
            }
        });

        matricula_jComboBox_profesor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        matricula_jComboBox_profesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ""}));
        matricula_jComboBox_profesor.setPreferredSize(new java.awt.Dimension(28, 20));

        matricula_jComboBox_materia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        matricula_jComboBox_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", }));
        matricula_jComboBox_materia.setPreferredSize(new java.awt.Dimension(28, 20));

        matricula_jComboBox_periodo_academico.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        matricula_jComboBox_periodo_academico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "","2024-1","2024-2","2025-1","2025-2","2026-1","2026-2","2027-1","2027-2","2028-1","2028-2","2029-1","2029-2"}));
        matricula_jComboBox_periodo_academico.setPreferredSize(new java.awt.Dimension(28, 20));

        javax.swing.GroupLayout jPanel_matriculaLayout = new javax.swing.GroupLayout(jPanel_matricula);
        jPanel_matricula.setLayout(jPanel_matriculaLayout);
        jPanel_matriculaLayout.setHorizontalGroup(
            jPanel_matriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_matriculaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel_matriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(matricula_btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_matriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel_matriculaLayout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addGap(18, 18, 18)
                            .addComponent(matricula_jComboBox_periodo_academico, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel_matriculaLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(18, 18, 18)
                            .addComponent(matricula_jComboBox_profesor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_matriculaLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(20, 20, 20)
                            .addComponent(matricula_jComboBox_materia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_matriculaLayout.createSequentialGroup()
                            .addComponent(jLabel19)
                            .addGap(18, 18, 18)
                            .addComponent(matricula_txt_codigo_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel_matriculaLayout.setVerticalGroup(
            jPanel_matriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_matriculaLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel_matriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(matricula_txt_codigo_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_matriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(matricula_jComboBox_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_matriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(matricula_jComboBox_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_matriculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(matricula_jComboBox_periodo_academico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addComponent(matricula_btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("tab4", jPanel_matricula);

        jPanel_nota.setBackground(new java.awt.Color(204, 204, 204));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Profesor:");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel28.setText("Materia:");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel29.setText("Estudiante:");

        nota_jComboBox_estudiante.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nota_jComboBox_estudiante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        nota_jComboBox_estudiante.setPreferredSize(new java.awt.Dimension(28, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel30.setText("Nota:");

        nota_btn_guardar.setText("Guardar");
        nota_btn_guardar.setPreferredSize(new java.awt.Dimension(100, 30));
        nota_btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota_btn_guardarActionPerformed(evt);
            }
        });

        nota_txt_nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota_txt_notaActionPerformed(evt);
            }
        });

        nota_jComboBox_materia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nota_jComboBox_materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        nota_jComboBox_materia.setPreferredSize(new java.awt.Dimension(28, 20));

        nota_jComboBox_profesor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nota_jComboBox_profesor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ""}));
        nota_jComboBox_profesor.setPreferredSize(new java.awt.Dimension(28, 20));

        javax.swing.GroupLayout jPanel_notaLayout = new javax.swing.GroupLayout(jPanel_nota);
        jPanel_nota.setLayout(jPanel_notaLayout);
        jPanel_notaLayout.setHorizontalGroup(
            jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_notaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nota_btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel_notaLayout.createSequentialGroup()
                        .addGroup(jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGroup(jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_notaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nota_jComboBox_estudiante, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nota_txt_nota, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)))
                            .addGroup(jPanel_notaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nota_jComboBox_profesor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nota_jComboBox_materia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(70, 70, 70))
        );
        jPanel_notaLayout.setVerticalGroup(
            jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_notaLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(nota_jComboBox_profesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(nota_jComboBox_materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(nota_jComboBox_estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_notaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(nota_txt_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(nota_btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("tab4", jPanel_nota);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, -30, 550, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_profesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profesorActionPerformed
        // profesor
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btn_profesorActionPerformed

    private void estudiante_btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiante_btn_guardarActionPerformed
        // guardamos los datos del estudiante
        
        System.out.println("guardando estudiante....");
        
        estudiante.setNombre(estudiante_txt_nombre.getText());
        estudiante.setEdad(Integer.parseInt(estudiante_txt_edad.getText()));
        estudiante.setIdentificacion(estudiante_txt_identificacion.getText());
        estudiante.setDireccion(estudiante_txt_direccion.getText());
        estudiante.setTelefono(estudiante_txt_telefono.getText());
        estudiante.setCorreo(estudiante_txt_correo.getText());
        estudiante.setCodigoEstudiante(estudiante_txt_codigo.getText());
        
        // Sexo
        javax.swing.JRadioButton selectedRadioButton = null;
        
        if (estudiante_jRadioButton_masculino.isSelected()) 
        {
            selectedRadioButton = estudiante_jRadioButton_masculino;
        }
        else if (estudiante_jRadioButton_femenino.isSelected()) 
        {
            selectedRadioButton = estudiante_jRadioButton_femenino;
        }
        else if (estudiante_jRadioButton_nobinario.isSelected()) 
        {
            selectedRadioButton = estudiante_jRadioButton_nobinario;
        }
        
        estudiante.setSexo(selectedRadioButton.getText());
        System.out.println(estudiante.getSexo());
    }//GEN-LAST:event_estudiante_btn_guardarActionPerformed

    private void estudiante_txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiante_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiante_txt_nombreActionPerformed

    private void btn_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_materiaActionPerformed
        // 
        jTabbedPane1.setSelectedIndex(1);
        
    }//GEN-LAST:event_btn_materiaActionPerformed

    private void btn_matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_matriculaActionPerformed
        // materia
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btn_matriculaActionPerformed

    private void btn_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estudianteActionPerformed
       // abrimos el panel de estudiantes
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btn_estudianteActionPerformed

    private void estudiante_txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiante_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiante_txt_edadActionPerformed

    private void estudiante_txt_identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiante_txt_identificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiante_txt_identificacionActionPerformed

    private void estudiante_txt_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiante_txt_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiante_txt_direccionActionPerformed

    private void estudiante_txt_telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiante_txt_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiante_txt_telefonoActionPerformed

    private void estudiante_txt_correoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiante_txt_correoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiante_txt_correoActionPerformed

    private void estudiante_txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiante_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiante_txt_codigoActionPerformed

    private void profesor_txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesor_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesor_txt_codigoActionPerformed

    private void profesor_txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesor_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_profesor_txt_nombreActionPerformed

    private void profesor_btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesor_btn_guardarActionPerformed
        // GUARDAMOS LOS DATOS DEL PROFESOR
        
        profesor.setNombreProfesor(profesor_txt_nombre.getText());
        profesor.setCodigoProfesor(profesor_txt_codigo.getText());
        
        // extraemos la informacion de las combobox
        profesor.setTituloDelProfesor((String) profesor_jComboBox_titulo.getSelectedItem());
        profesor.setTipoDeVinculacion((String) profesor_jComboBox_tipo_de_vinculacion.getSelectedItem());
        
        matricula_jComboBox_profesor.addItem(profesor.getNombreProfesor() );
        
    }//GEN-LAST:event_profesor_btn_guardarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // Cerrar ventana
        System.exit(WIDTH);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_notaActionPerformed
        //nota
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_btn_notaActionPerformed

    private void matricula_txt_codigo_estudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula_txt_codigo_estudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula_txt_codigo_estudianteActionPerformed

    private void materia_txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materia_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materia_txt_nombreActionPerformed

    private void materia_txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materia_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materia_txt_codigoActionPerformed

    private void profesor_btn_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profesor_btn_guardar1ActionPerformed
        // GUARDAMOS LA INFO DE LA MATERIA
        
        materia.setMateria(materia_txt_nombre.getText());
        materia.setCodigoMateria(materia_txt_codigo.getText());
        materia.setNumDeCreditos(Integer.parseInt((String) materia_jComboBox_num_creditos.getSelectedItem()));
        materia.setSemestreDeLaMateria((Integer.parseInt((String) materia_jComboBox_semestre.getSelectedItem())));
        
        // agregamos la materia a la matricula
        matricula_jComboBox_materia.addItem(materia.getMateria());
        
        nota_jComboBox_profesor.addItem(profesor.getNombreProfesor()+" - " + profesor.getCodigoProfesor());
        nota_jComboBox_materia.addItem(materia.getMateria() + " - " + materia.getCodigoMateria());
        nota_jComboBox_estudiante.addItem(estudiante.getNombre() + " - " + estudiante.getCodigoEstudiante());
        
    }//GEN-LAST:event_profesor_btn_guardar1ActionPerformed

    private void matricula_btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula_btn_guardarActionPerformed
        // Guardamos los datos de la matricula
        
        matricula.setPeriodoAcademico((String) matricula_jComboBox_periodo_academico.getSelectedItem());
        
    }//GEN-LAST:event_matricula_btn_guardarActionPerformed

    private void estudiante_jRadioButton_femeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estudiante_jRadioButton_femeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estudiante_jRadioButton_femeninoActionPerformed

    private void nota_btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota_btn_guardarActionPerformed
        // GUARDAMOS LA NOTA
        
        matricula.setNota(Float.parseFloat(nota_txt_nota.getText()));
        
        JOptionPane.showMessageDialog(null, "¡Nota Guardada con éxito!");
        
        
    }//GEN-LAST:event_nota_btn_guardarActionPerformed

    private void nota_txt_notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota_txt_notaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota_txt_notaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_estudiante;
    private javax.swing.JButton btn_materia;
    private javax.swing.JButton btn_matricula;
    private javax.swing.JButton btn_nota;
    private javax.swing.JButton btn_profesor;
    private javax.swing.JButton btn_salir;
    private javax.swing.ButtonGroup estudiante_btnGroup_sexo;
    private javax.swing.JButton estudiante_btn_guardar;
    private javax.swing.JRadioButton estudiante_jRadioButton_femenino;
    private javax.swing.JRadioButton estudiante_jRadioButton_masculino;
    private javax.swing.JRadioButton estudiante_jRadioButton_nobinario;
    private javax.swing.JTextField estudiante_txt_codigo;
    private javax.swing.JTextField estudiante_txt_correo;
    private javax.swing.JTextField estudiante_txt_direccion;
    private javax.swing.JTextField estudiante_txt_edad;
    private javax.swing.JTextField estudiante_txt_identificacion;
    private javax.swing.JTextField estudiante_txt_nombre;
    private javax.swing.JTextField estudiante_txt_telefono;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel_estudiante;
    private javax.swing.JPanel jPanel_fondo_izquierda;
    private javax.swing.JPanel jPanel_materia;
    private javax.swing.JPanel jPanel_matricula;
    private javax.swing.JPanel jPanel_nota;
    private javax.swing.JPanel jPanel_profesor;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> materia_jComboBox_num_creditos;
    private javax.swing.JComboBox<String> materia_jComboBox_semestre;
    private javax.swing.JTextField materia_txt_codigo;
    private javax.swing.JTextField materia_txt_nombre;
    private javax.swing.JButton matricula_btn_guardar;
    private javax.swing.JComboBox<String> matricula_jComboBox_materia;
    private javax.swing.JComboBox<String> matricula_jComboBox_periodo_academico;
    private javax.swing.JComboBox<String> matricula_jComboBox_profesor;
    private javax.swing.JTextField matricula_txt_codigo_estudiante;
    private javax.swing.JButton nota_btn_guardar;
    private javax.swing.JComboBox<String> nota_jComboBox_estudiante;
    private javax.swing.JComboBox<String> nota_jComboBox_materia;
    private javax.swing.JComboBox<String> nota_jComboBox_profesor;
    private javax.swing.JTextField nota_txt_nota;
    private javax.swing.JButton profesor_btn_guardar;
    private javax.swing.JButton profesor_btn_guardar1;
    private javax.swing.JComboBox<String> profesor_jComboBox_tipo_de_vinculacion;
    private javax.swing.JComboBox<String> profesor_jComboBox_titulo;
    private javax.swing.JTextField profesor_txt_codigo;
    private javax.swing.JTextField profesor_txt_nombre;
    // End of variables declaration//GEN-END:variables
}
